### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by adildg**
fix typo

### CODE REVIEW

**Comment by thelicato** [comment]
Hello, I decided to convert this project in a [Python Poetry](https://python-poetry.org/) application. Give me an hour and I will fix it

**Comment by thelicato** [comment]
I successfully switched the project to Python Poetry and published it on PyPI. Now you can install it with:
```
pip install invisibile-backdoor-detector
```

**Comment by adildg** [comment]
> I successfully switched the project to Python Poetry and published it on PyPI. Now you can install it with:
> 
> ```
> pip install invisibile-backdoor-detector
> ```

What a perfect timing 🕺🏻 
Thanks <3

**Comment by thelicato** [comment]
Well thanks to you for the PR!

**Pull request closed without merging**
